# protect pets | default: true
Settings:
  Tamed_Pet_Protect: true
  Keep_PvP_After_Logout: false
  MySQL: false
# message | parameter: <player> <target> <pet> | colorchar: &
Message:
  PvP_Toggle_ON: '&6Dein PvP mode ist aktiviert!' #available: <player>
  PvP_Toggle_OFF: '&6Dein PvP mode ist deaktiviert!' #available: <player>
  PvP_Toggle_Other_ON: '&6Du hast den Pvp mode von &b<target> &6aktiviert!' #available: <player> <target>
  PvP_Toggle_Other_OFF: '&6Du hast den Pvp mode von &b<target> &6deaktiviert!' #available: <player> <target>
  PvP_Toggle_Other_ON_Target: '&b<player> &6hat dein Pvp mode aktiviert!' #available: <player> <target>
  PvP_Toggle_Other_OFF_Target: '&b<player> &6hat dein Pvp mode deaktiviert!' #available: <player> <target>
  PvP_False_Both: '&6Du und &b<target> &6haben PVP deaktiviert!' #available: <player> <target>
  PvP_False_Self: '&6Du hast PVP deaktiviert!' #available: <player> <target>
  PvP_False_Other: '&b<target> &6hat PVP deaktiviert!' #available: <player> <target>
  PvP_Offline: '&c<target> ist offline!' #available: <player> <target>
  PvP_Pet_Protect: '&6Diese(r) &b<pet> &6steht unter dem Schutz von &b<target>&6!' #available: <pet> <player> <target>
  PvP_List: '&6PvP Liste:' #NoParameter
  PvP_NotFound: '&cSpieler nicht gefunden' #NoParameter
  PvP_Usage: '&cBitte /pvp <player> <true/false> benutzen!' #NoParameter
  PvP_Wrong_Command: '&cBefehl nicht erkannt!' #NoParameter
  PvP_NoPerm: '&cKeine Berechtigung!' #NoParameter
  PvP_Nobody: '&cNiemand!' #NoParameter
# MySQL | Need SELECT, INSERT, UPDATE, DELETE and CREATE permissions
MySQL:
  Host: '127.0.0.1'
  Port: '3306'
  Database: 'test_minecraft_pvplist'
  Username: 'pvplist'
  Password: 'test123'