# protect pets | default: true
Settings:
  Tamed_Pet_Protect: true
  Debug: false

# message | parameter: <player> <target> <pet> | color char: &
Message:
  PvP_Toggle_ON: '&6Dein PvP Modus ist aktiviert!' #available: <player>
  PvP_Toggle_OFF: '&6Dein PvP Modus ist deaktiviert!' #available: <player>
  PvP_Toggle_Other_ON: '&6Du hast den Pvp Modus von &b<target> &6aktiviert!' #available: <player> <target>
  PvP_Toggle_Other_OFF: '&6Du hast den Pvp Modus von &b<target> &6deaktiviert!' #available: <player> <target>
  PvP_Toggle_Other_ON_Target: '&b<player> &6hat dein Pvp Modus aktiviert!' #available: <player> <target>
  PvP_Toggle_Other_OFF_Target: '&b<player> &6hat dein Pvp Modus deaktiviert!' #available: <player> <target>
  PvP_False_Both: '&6Du und &b<target> &6haben PVP deaktiviert!' #available: <player> <target>
  PvP_False_Self: '&6Du hast PVP deaktiviert!' #available: <player> <target>
  PvP_False_Other: '&b<target> &6hat PVP deaktiviert!' #available: <player> <target>
  PvP_State_ON: '&6Dein PvP Modus ist eingeschaltet!' #available: <player>
  PvP_State_OFF: '&6Dein PvP Modus ist ausgeschaltet!' #available: <player>
  PvP_Pet_Protect: '&6Diese(r) &b<pet> &6steht unter dem Schutz von &b<target>&6!' #available: <pet> <player> <target>
  PvP_List: '&6Diese Spieler leben gefährlich!' #NoParameter
  PvP_NotFound: '&cSpieler nicht gefunden' #NoParameter
  PvP_Usage: '&cBitte /pvp <player> <true/false> benutzen!' #NoParameter
  PvP_Wrong_Command: '&cBefehl nicht erkannt!' #NoParameter
  PvP_NoPerm: '&cKeine Berechtigung!' #NoParameter
  PvP_Nobody: '&cNiemand!' #NoParameter
  PvP_Error: '&cDein Befehl konnte nicht verarbeitet. Bitte versuchs erneut!' #NoParameter

BlockedWorldList:
 # - Spawn
 # - Eventworld

# MySQL | Need SELECT, INSERT, UPDATE, DELETE and CREATE permissions
MySQL:
  Host: '127.0.0.1'
  Port: 3306
  Database: 'yourDatabase'
  TablePrefix: 'pt_'
  Username: 'yourUsername'
  Password: 'yourPassword'

BungeeCord:
  Enable: false