name: PvPToggle
version: 1.0
api-version: 1.13
main: de.crafttogether.pvptoggle.PvPTogglePlugin

commands:
   pvp:
      description: toggle your pvp mode
   pvplist:
      description: show a pvplist
   pvpstate:
      description: show your pvp state